### ISSUE TITLE
How to solve the fatal error: Unable to locate credentials

### ISSUE THREAD

**Issue by xiaohai2019** [Doudna-lab/snakedali#1]
Hi Daniel,
When I download the pre-built AFDB_clustering database using the command below, it returned a fatal error.

command: aws s3 cp s3://snakedali.db/pdb_files_DAT.tar.gz ./
returned error: fatal error: Unable to locate credentials

Could you please help me with this? How can I solve this problem?

Thanks a lot!

Xiaohai

**Comment by iwangtoknow** [comment]
@xiaohai2019 Check how to use AWS CLI, you need to setup an account.

**Comment by dbellieny** [comment]
Thanks for your comment @iwangtoknow!
That is correct, @xiaohai2019. You should first set up an account on AWS and then install the AWS CLI to pull the Snakedali database from the AWS S3 bucket.

I amended the README.md to include further instructions in case more users encounter the same issue.

**Comment by xiaohai2019** [comment]
Thanks for both of you to reply me.
